apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-demo-service
spec:
  type: LoadBalancer
  selector:
    app: docker-k8s-demo
  ports:
    - protocol: TCP
      port: 60000
      targetPort: 8080